In [251]:
import pandas as pd
import numpy as np
import json
# Place Yelp dataset in ../yelp-dataset
yelp_dataset_path = '../yelp-dataset/'
print(yelp_dataset_path + 'yelp_academic_dataset_business.json')

data = [json.loads(line) for line in 
        open(yelp_dataset_path+'yelp_academic_dataset_business.json', 'r', encoding="utf8")]

../yelp-dataset/yelp_academic_dataset_business.json


FileNotFoundError: [Errno 2] No such file or directory: '../yelp-dataset/yelp_academic_dataset_business.json'

In [160]:
data = [x for x in data if x['city']=='Toronto']
data = np.array(data) # Convert list to numpy array

In [161]:
len(tor_total_business)

519692

In [162]:
ok = np.array(tor_total_business)

In [7]:
test = []
for i in range(len(tor_total_business)):
    test.append(tor_total_business[i]['user_id'])
test = np.array(test)

In [8]:
unique, counts = np.unique(test, return_counts=True)
ok =dict(zip(unique, counts))
final_l = []
recs=0
for i in range(len(counts)):
    if counts[i]>=15:
        final_l.append(unique[i])
        recs += counts[i]

In [9]:
final_l = np.array(final_l)

In [10]:
with open(yelp_dataset_path + 'yelp_academic_dataset_review.json') as myfile:
    head = [next(myfile) for x in range(1)]
print(head)

['{"review_id":"xQY8N_XvtGbearJ5X4QryQ","user_id":"OwjRMXRC0KyPrIlcjaXeFQ","business_id":"-MhfebM0QIsKt87iDN-FNw","stars":2.0,"useful":5,"funny":0,"cool":0,"text":"As someone who has worked with many museums, I was eager to visit this gallery on my most recent trip to Las Vegas. When I saw they would be showing infamous eggs of the House of Faberge from the Virginia Museum of Fine Arts (VMFA), I knew I had to go!\\n\\nTucked away near the gelateria and the garden, the Gallery is pretty much hidden from view. It\'s what real estate agents would call \\"cozy\\" or \\"charming\\" - basically any euphemism for small.\\n\\nThat being said, you can still see wonderful art at a gallery of any size, so why the two *s you ask? Let me tell you:\\n\\n* pricing for this, while relatively inexpensive for a Las Vegas attraction, is completely over the top. For the space and the amount of art you can fit in there, it is a bit much.\\n* it\'s not kid friendly at all. Seriously, don\'t bring them.\\n* 

# Βημα 2

In [1]:
import pandas as pd 
import math
import numpy as np
import json

table_R = pd.read_csv("pruned_data.csv", header = None)
new_header = ['user_id', 'business_id', 'rating']
table_R.columns = new_header[:]
print(table_R)

                       user_id             business_id  rating
0       TZQSUDDcA4ek5gBd6BzcjA  qUWqjjjfpB2-4P3He5rsKw     4.0
1       TZQSUDDcA4ek5gBd6BzcjA  6n_MDeYxU1ihB38be9TkVA     4.0
2       TZQSUDDcA4ek5gBd6BzcjA  jo4KmAqlZ7vxjHIP7IIkAw     5.0
3       TZQSUDDcA4ek5gBd6BzcjA  dsAcgF6qtZy2m6d_yWCrGQ     4.0
4       TZQSUDDcA4ek5gBd6BzcjA  siaRCT2-PkyeXUVKrywcTg     4.0
...                        ...                     ...     ...
197107  3L3CI2Om_2SE3T6hxrJKPQ  j_hB9Gt3VMJAbA2JyvyFjw     4.0
197108  3L3CI2Om_2SE3T6hxrJKPQ  WKcVegcUjAld1S737a_QHw     4.0
197109  3L3CI2Om_2SE3T6hxrJKPQ  1FL3oE2mqq_EFAYPd1TWUg     5.0
197110  3L3CI2Om_2SE3T6hxrJKPQ  hlrZHM4D48XiQtXh6cRg_w     1.0
197111  3L3CI2Om_2SE3T6hxrJKPQ  _cVCzKQGt23KKW1M07Yvkw     5.0

[197112 rows x 3 columns]


In [2]:
print("Sample data should have {} rows \n".format(math.ceil(len(table_R)*0.05)))
sample_data = table_R.sample(frac=0.05)
print(len(sample_data))

Sample data should have 9856 rows 

9856


In [3]:
print(sample_data.index) # sampled indexes

# Setting sample ratings to Nan
for index in sample_data.index:
    table_R['rating'].iloc[index] = np.nan

Int64Index([152561,   4316,  69273,  99636, 146799,  52793,  67961,  76069,
            115115,  33582,
            ...
             91505, 147260, 118358,  70024,  18687,  36918, 154144,  65590,
            195806,  85341],
           dtype='int64', length=9856)


/home/left/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [4]:
tableR = table_R.to_numpy()
unique_users, countsU = np.unique(tableR[:,0], return_counts=True)
unique_business, countsB = np.unique(tableR[:,1], return_counts=True)

In [5]:
sparse_array = np.zeros((len(unique_users), len(unique_business)))
# Create the sparse_array
for i in range(len(unique_users)):
    business_index = np.where( unique_users[i] == table_R['user_id'])
    
    for j in range(len(business_index[0])):
        temp_business = table_R['business_id'][business_index[0][j]] #take business_id for given index
        unique_business_ind = np.where(temp_business == unique_business)
        sparse_array[i][unique_business_ind[0][0]] = table_R['rating'][business_index[0][j]]

In [6]:
#cc = 0
#for i in range(sparse_array.shape[0]):
#    for j in range(sparse_array.shape[1]):
#        if not math.isnan(sparse_array[i][j]):
#            cc+=sparse_array[i][j]
#cc

In [7]:
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity
spars = np.nan_to_num(sparse_array) # Change nan values from sparse_array to zero
similarities = cosine_similarity(spars)
sample_array = sample_data.to_numpy()

In [8]:
def find_index(user_id):
    ind = np.where(user_id  == unique_users)
    return ind[0][0]
def find_business(business_id):
    ind = np.where(business_id == unique_business)
    return ind[0][0]

In [9]:
def get_top_similarities(user1, common_users, ratings):
    user_ind1 = find_index(user1)
    similar = []
    for i in range(len(common_users)):
        temp_ind = find_index(common_users[i])
        similar.append([common_users[i], float(similarities[user_ind1][temp_ind]), int(ratings[i])])
    return similar

In [10]:
def UFC_prediction(similarity, rating):
    numerator = 0
    denominator = np.sum(similarity)
    for i in range(len(similarity)):
        numerator += similarity[i]*rating[i]
    return numerator/denominator
        

In [11]:
from operator import itemgetter
predictions = []
for i in range(sample_array.shape[0]): # For every pair (u,b) that have missing rating
    common_ratings = []
    common_users = []
    business_index = find_business(sample_array[i][1]) # Get business index
    common_users_indexes = np.nonzero(spars[:,business_index]) # FIND INDEXES FOR NONZERO VALUES ONLY!
    for j in range(len(common_users_indexes[0])): # For every row in spars- (Actually for every user)
        common_ratings.append(spars[common_users_indexes[0][j]][business_index]) # Append ratings
        common_users.append(unique_users[common_users_indexes[0][j]]) # Append the user_id
    
    most_k_similar_users = get_top_similarities(sample_array[i][0], common_users, common_ratings)
    
    vectors = np.array(sorted(most_k_similar_users, key=itemgetter(1), reverse=True))
    vectors = vectors[:5]
    vectors # user_id, similarity and rating for most k-similar users
    similarity_vector = vectors[:,1].astype(float)
    ratings_vector = vectors[:,2].astype(int)
    prediction = UFC_prediction(similarity_vector, ratings_vector)
    predictions.append(prediction)

In [14]:
sample_data

user_id             business_id  rating
152561  xavCcqaAiDpWOXe_V6HI2g  a8pmtlVKf7NiSLI-4KejIw     1.0
4316    CxDOIDnH8gp9KXzpBHJYXw  gHmkE8VoNjJZDLVdTpJPOw     3.0
69273   17Okw7mKDKhvKQCBnl_iRQ  dAmVTQ6ukuLh4UxTmBoRkg     5.0
99636   2pVj1Hid6_Iq3Th9xI0aOQ  JMiaNitMzMbJm6Kh0RbT5A     4.0
146799  7Mbh-hCSS6UVDNmVlvZhEQ  73_UT7fZ7mzXcguX8-oSuQ     4.0
...                        ...                     ...     ...
36918   QlRsVCCytArycuuKSyUBLg  iT053N_wdX7Ryr5lLCtLfg     3.0
154144  bQxs2JWnnXIJU5bkxCovNw  r_BrIgzYcwo1NAuG9dLbpg     5.0
65590   TGT3T6FMq5xivl_W8HiuDg  SjgeuBlgKER9yegpoxT99w     5.0
195806  JxR29xafQIMaEPRcRgZAmA  2Q89PhkcyT9uZnQORmqMKg     4.0
85341   2_J91lZzqXOYyYeNcVd2YQ  KpEu3vvj1ruoID0T3lmD4Q     4.0

[9856 rows x 3 columns]

In [28]:
true_ratings = sample_data['rating']
true_ratings = true_ratings.to_numpy()
true_ratings

array([1., 3., 5., ..., 5., 4., 4.])

In [32]:
predicted_ratings = np.array(predictions)
predicted_ratings

array([2.81620316, 2.75184608, 4.40637247, ..., 4.54277184, 3.47805722,
       3.84961428])

In [33]:
differences = abs(true_ratings - predicted_ratings)

In [34]:
differences

array([1.81620316, 0.24815392, 0.59362753, ..., 0.45722816, 0.52194278,
       0.15038572])

In [ ]:
np,meadifferences